use proc_macro_crate::crate_name;
use proc_macro2::Span;
use syn::{Ident, ItemFn, Meta};

/// Determines if this block of code was [generated by near_bindgen].
/// Heuristic used is to check for the shape of the generated wrapper functions
/// (`pub extern "C"` + `#[no_mangle]`), falling back to the `#[cfg]` markers that
/// near_bindgen attaches to them (visible to proc macros only on rustc < 1.87).
/// TODO: How to make this 100% safe. Discuss with near-sdk team
///
/// [generated by near_bindgen]: https://github.com/near/near-sdk-rs/issues/722
pub(crate) fn is_near_bindgen_wrapped_or_marshall(item: &ItemFn) -> bool {
    // near_bindgen-generated wrapper functions are `pub extern "C"` and `#[no_mangle]`
    // (`#[unsafe(no_mangle)]` on newer near-sdk). Detect that shape directly: since
    // rustc 1.87, `#[cfg]` attributes are evaluated and stripped before attribute proc
    // macros run, so the cfg-token heuristic below no longer sees the generated
    // `#[cfg(target_arch = "wasm32")]` marker. User-written functions -- including
    // receiverless entry points like `#[init(ignore_state)]` migrations annotated with
    // `#[only(self)]` -- are never `extern "C"` + `#[no_mangle]`, so they keep being
    // processed by the plugin macros.
    let is_extern_c = item
        .sig
        .abi
        .as_ref()
        .is_some_and(|abi| abi.name.as_ref().is_none_or(|name| name.value() == "C"));
    let has_no_mangle = item.attrs.iter().any(|attr| match &attr.meta {
        Meta::Path(path) => path.is_ident("no_mangle"),
        Meta::List(list) => list.path.is_ident("unsafe") && list.tokens.to_string() == "no_mangle",
        _ => false,
    });
    if is_extern_c && has_no_mangle {
        return true;
    }
    // Legacy heuristic for rustc < 1.87, where the generated `#[cfg]` markers are still
    // visible to this macro.
    let pattern1 = "target_arch = \"wasm32\"";
    let pattern2 = "not(target_arch = \"wasm32\")";
    item.attrs.iter().any(|attr| {
        if let Meta::List(meta_list) = &attr.meta {
            let seq = meta_list.tokens.to_string();
            return seq == pattern1 || seq == pattern2;
        }
        false
    })
}

/// Returns an identifier for the name of the crate which is imported by plugin users.
pub(crate) fn cratename() -> Ident {
    Ident::new(
        &crate_name("near-plugins").unwrap_or_else(|_| "near_plugins".to_string()),
        Span::call_site(),
    )
}

/// Injects extra code into a function.
pub(crate) fn add_extra_code_to_fn(
    fn_code: &ItemFn,
    extra_code: proc_macro2::TokenStream,
) -> proc_macro::TokenStream {
    let ItemFn {
        attrs,
        vis,
        sig,
        block,
    } = fn_code;
    let stmts = &block.stmts;

    // https://stackoverflow.com/a/66851407
    quote::quote! {
        #(#attrs)* #vis #sig {
            #extra_code
            #(#stmts)*
        }
    }
    .into()
}
